services:
  server:
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
    env_file:
      - ./global.env
  
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
  
  client:
    build: ../client
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./client/src/:/app/src/
    env_file:
      - ./global.env


    